# https://www.golinuxcloud.com/kubernetes-init-containers/

apiVersion: v1
kind: Pod
metadata:
  name: init-container-example-1
spec:
  initContainers:
  - name: sleepy
    image: alpine
    command: ['sleep', '60']
  containers:
  - name: web
    image: nginx